{{- if or .Values.runnerRegistrationToken .Values.runnerToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
type: Opaque
data:
  cloudsql-instance-credentials: {{ default "" .Values.runnerRegistrationToken | b64enc | quote }}
{{- end -}}
